//cardData
const cardData = [
  {
    id: 1,
    image: "/cards/dummycard.webp",
    altText: "card",
    width: 300,
    height: 100,
    subtitle: "Standard",
    price: "200 starting at RS.200.00",
  },
  {
    id: 1,
    image: "/cards/standard-card.webp",
    altText: "another card",
    width: 300,
    height: 100,
    subtitle: "Standard",
    price: "300 starting at RS.300.00",
  },
  {
    id: 1,
    image: "/cards/dummycard.webp",
    altText: "another card",
    width: 300,
    height: 100,
    subtitle: "Standard",
    price: "300 starting at RS.300.00",
  },
  {
    id: 1,
    image: "/cards/dummycard.webp",
    altText: "another card",
    width: 300,
    height: 100,
    subtitle: "Standard",
    price: "300 starting at RS.300.00",
  },
  {
    id: 1,
    image: "/cards/dummycard.webp",
    altText: "another card",
    width: 300,
    height: 100,
    subtitle: "Standard",
    price: "150 starting at RS.300.00",
  },
  {
    id: 2,
    image: "/cards/dummycard.webp",
    altText: "another card",
    width: 300,
    height: 100,
    subtitle: "Standard",
    price: "100 starting at RS.300.00",
  },
  {
    id: 3,
    image: "/cards/dummycard.webp",
    altText: "another card",
    width: 300,
    height: 100,
    subtitle: "Standard",
    price: "100 starting at RS.300.00",
  },
  {
    id: 3,
    image: "/cards/dummycard.webp",
    altText: "another card",
    width: 300,
    height: 100,
    subtitle: "Standard",
    price: "100 starting at RS.300.00",
  },
  {
    id: 3,
    image: "/cards/dummycard.webp",
    altText: "another card",
    width: 300,
    height: 100,
    subtitle: "Standard",
    price: "100 starting at RS.300.00",
  },
];

export default cardData;
