const myuploadsData = [
    {
        id:"1",
        imageUrl:"/cards/cards-2.jpeg",
        Filename:"visiting_card.pdf",
        date:"01-02-2024",
    },
    {
        id:"2",
        imageUrl:"/cards/businesscard.jpg",
        Filename:"visiting_card.pdf",
        date:"04-02-2024",
    },
    {
        id:"3",
        imageUrl:"/cards/standuppouch.jpg",
        Filename:"standup.pdf",
        date:"17-02-2024",
    },
    {
        id:"4",
        imageUrl:"/cards/cards-2.jpeg",
        Filename:"visiting_card.pdf",
        date:"13-03-2024",
    },
    {
        id:"5",
        imageUrl:"/cards/cards-2.jpeg",
        Filename:"visiting_card.pdf",
        date:"21-03-2024",
    },
    {
        id:"6",
        imageUrl:"/cards/cards-2.jpeg",
        Filename:"visiting_card.pdf",
        date:"01-04-2024",
    },
    {
        id:"7",
        imageUrl:"/cards/cards-2.jpeg",
        Filename:"visiting_card.pdf",
        date:"01-04-2024",
    },
    
];
export default myuploadsData;